
CREATE TABLE users(
    user_id SERIAL PRIMARY KEY NOT NULL,
    profile_pic TEXT,
    email VARCHAR(200),
    password VARCHAR(200),
    first_name VARCHAR(200),
    last_name VARCHAR(200),
    account_creation_date VARCHAR(50)
);

CREATE TABLE shoes(
    shoe_id SERIAL PRIMARY KEY NOT NULL,
    shoe_model VARCHAR(200),
    brand VARCHAR(200),
    colorway VARCHAR(200),
    price INTEGER,
    description VARCHAR(1350),
    year_released NUMERIC(4,0),
    image_1_url text,
    image_2_url text,
    image_3_url text,
    image_4_url text
);

CREATE TABLE user_shoes(
    user_shoe_id SERIAL PRIMARY KEY NOT NULL,
    shoe_id INTEGER,
    user_id INTEGER,
    size NUMERIC(3,1),
    for_sale BOOLEAN,
    bought_price INTEGER,
    sale_price INTEGER,
    details VARCHAR(1350),
    image_1_url text,
    image_2_url text,
    image_3_url text,
    image_4_url text
);

create table rooms (
room_id varchar primary key
)

create table chats (
chat_id serial primary key,
message text,
user_id int, 
room_id varchar
)

CREATE TABLE FAVORITES(
    favorite_id SERIAL PRIMARY KEY NOT NULL,
    shoe_id INTEGER,
    user_id INTEGER,
    date_added TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FOLLOWING(
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER,
    followed_user_id INTEGER,
    date_added VARCHAR(50)
);


INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES
 ('Air Mag', 'Nike', '2016 Air Mag', 15,000, 'The Nike MAG is a limited edition shoe created by Nike Inc. It is a replica of a shoe featured in Back to the Future Part II. The Nike Mag was originally released for sale in 2011 and again in 2016. Both launches were extremely limited in quantity.', 2016, 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_1.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_2.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_3.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_7.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Cortez', 'Nike', 'Forrest Gump', 80, "Just like the film, this model Cortez is the same as models released by Nike in the 1970's.", 2017, 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300', 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img32.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300', 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img24.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300', 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Air Foamposite Pro', 'Nike', 'Color Shift', 230, 'Become a pro at the sneaker game and cop the Air Foamposite Pro Color Shift. This Air Foamposite Pro comes with a dirty rose gold upper, black Nike “Swoosh”, black midsole, and a black sole. These sneakers released in April 2019 and retailed for $230.', 2019, 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-4.jpg','https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-2-1.jpg', 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-Price-4.jpg', 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-Price-5.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Air Max 270 Doernbecher', 'Nike', 'Black/Metallic Gold-Medium Olive', 150, 'Blend in with the deep pits of the sneaker world while rocking the Air Max 270 Doernbecher (2018). This Air Max 270 comes with an army fatigue upper, gold Nike “Swoosh”, black midsole with gold accents, and a black sole. These sneakers released in December 2018 and retailed for $150.', 2018, 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img31.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img21.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Epic React Flyknit', 'Nike', 'Wolf-Grey/White-Cool Grey-Pure Platinum', 150, 'Take your everyday training session or casual day to epic new heights in the Women''s Nike Epic React Flyknit Running Shoes.', 2018, 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Kyrie V Concepts Ikhet', 'Nike', 'Multi-Color', 180, 'This Nike Kyrie 5 is inspired by Kyrie’s Hamsa hand tattoo. Its Sandy Beige upper nods to the age of Ancient Egypt and pyramids, while having a chiseled Grey Swoosh, Red tongue to represent the nose of the Sphinx before it decayed, atop a Purple sole that represents the sunset against the pyramids. Dual branding on the tongue shroud, along with Egyptian hieroglyphs on each heel completes the design.', 2018, 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300', 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300', 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300', 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Air Max Air Max Day', 'Nike', 'White/Rift Blue-Hyper Jade-Midnight Navy', 150, 'This Nike Kyrie 5 is inspired by Kyrie’s Hamsa hand tattoo. Its Sandy Beige upper nods to the age of Ancient Egypt and pyramids, while having a chiseled Grey Swoosh, Red tongue to represent the nose of the Sphinx before it decayed, atop a Purple sole that represents the sunset against the pyramids. Dual branding on the tongue shroud, along with Egyptian hieroglyphs on each heel completes the design.', 2015, 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img13.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike VaporMax Premier Flyknit', 'Nike', 'Black/Metallic Silver-White', 225, 'Nike refers to their VaporMax sole as if you’re walking on clouds. Expanding their VaporMax series, the Swoosh has officially introduced the VaporMax Premier Flyknit. This particular colorway of the shoe comes dressed in a Black, Metallic Silver, White, and Anthracite color scheme. It features a remarkably comfortable design, locked down with a criss-cross leather strap and magnetic closure. Add details includes 3M Reflective hints on its Swoosh logo.', 2018, 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300', 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img29.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300', 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300', 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Dunk SB Low Walk of Fame Brooklyn Projects', 'Nike', 'Black/Metallic Gold-Light Redwood', 120, 'The Brooklyn Projects x Nike SB Walk of Fame was issued in 2013. Inspired by the Hollywood landmark in Los Angeles, California, the colors presented on the sneaker are similar to those seen on the Hollywood Boulevard. The sneaker was released in selected locations of Los Angeles, Japan, and Canada.', 2013, 'https://stockx-360.imgix.net/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Images/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549069835&w=2200', 'https://stockx-360.imgix.net/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Images/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Lv2/img27.jpg?auto=format,compress&q=90&updated_at=1549069835&w=2200', 'https://stockx-360.imgix.net/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Images/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1549069835&w=2200', 'https://stockx-360.imgix.net/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Images/Nike-Dunk-SB-Low-Walk-Of-Fame-Brooklyn-Projects/Lv2/img07.jpg?auto=format,compress&q=90&updated_at=1549069835&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Zoom Pegasus 35 Turbo', 'Nike', 'Barely Grey/Hot Punch-Black', 180, 'The Sneaker either comes with "Zoom" or "Nike Zoom" logo on the sole depending on which region it was sold in. The Nike Zoom Pegasus Turbo Wolf Grey Hot Punch marks one of Nike''s most innovative running shoes to date. Using its brand new Zoom X technology, these shoes will keep your fits fresh and feet cozy all day long. This pair utilizes a translucent upper with a hot punch racing stripe running from the tongue all the way down the laces to the underside of the shoes. These are definitely Lightning McQueen approved. If you are on the market for one of the hottest running shoes of 2018 or just for a fresh pair of kicks, the Nike Zoom Pegasus Turbo is for you. This pair released in July 2018 for $180.', 2018, 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img26.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Shaq Attack', 'Reebok', 'Blue', 160, 'Over 20 years after it originally released, the Reebok Shaq Attaq “Away” in black and Azure Blue returned to stores as a retro in 2013. Originally released in 1992, the Shaq Attaq got its name from Shaquille O’Neal’s ability to attack the rim with avengeance.', 2013, 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_02.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_03.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_04.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_01.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Freestyle HI', 'Reebok', 'White', 75, 'On-trend, in-vogue and all-the-craze. Features a leather upper that is supportive and comfortable. An EVA midsole and terry cloth lining provide lightweight cushioning so you keep moving long after others have stopped.', 2018, 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/f66b4a0987b34c59bed9a44c0189064c_9366/Freestyle_Hi_White_70_01_standard.jpg', 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/b5cd3946602c4da5b68da44c018922a2_9366/Freestyle_Hi_White_70_02_standard.jpg', 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/bfc23e6a20c84f519075a44c018951b5_9366/Freestyle_Hi_White_70_04_standard.jpg', 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/53283fde763e4ad99f0da44c01896904_9366/Freestyle_Hi_White_70_05_standard.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Instapump Fury', 'Reebok', 'Grinch', 200, 'Reebok Classics has released their holiday inspired Reebok Insta Pump Fury Grinch edition just in time for Christmas.Inspired by How the Grinch Stole Christmas, this Reebok Insta Pump Fury comes dressed in a Semi Solar Green, Scarlet, Pine Green and Gold color scheme. Featuring a Green faux fur underlays with Red overlays and Metallic Gold branding wrap.', 2016, 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img35.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img26.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img22.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img07.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Classic Nylon', 'Reebok', 'Nipsey Hussle Royal', 125, 'Self-made Los Angeles rap stalwart Nipsey Hussle has joined forces with Reebok for an all-blue Classic Nylon, paying homage to Nipsey’s hometown Dodgers and his oft-referenced neighborhood Crip affiliation. The shoe features an upper composed of nylon and premium suede, while a faint white snakeskin pattern on the heel and Reebok chevron provides just enough contrast. The heel features a great deal of detail as well, with “Rich Rollin” (the name of one of Nipsey’s classic songs) embroidered on the top, and his hometown streets of Crenshaw and Slauson debossed on the bottom. This isn’t the first time Reebok has worked with a famous West Coast rapper on a shoe that draws inspiration from LA’s gang culture either. Before Kendrick Lamar left the brand to join forces with Nike, he also collaborated on a pair of Reebok Classics that aimed to be a call to unity for LA’s Bloods and Crips. The Nipsey Hussle x Reebok Classic Nylon releases this February 17th.', 2018, 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img36.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200', 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img29.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200', 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img22.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200', 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Classic Nylon', 'Reebok', 'Big Shaqtus', 160, 'The Reebok Shaq Attaq “Big Shaqtus” retro pays homage to Shaquille O’Neal’s days in the desert as a member of the Phoenix Suns. Although Shaq’s era in Phoenix was short-lived, in the year he was there Phoenix hosted the NBA All Star Game and Shaquille O’Neal was voted on to the Western Conference team for his 15th All Star appearance and named co-MVP alongside his former teammate Kobe Bryant. The Big Shaqtus Shaq Attaq was initially nicknamed “Suns” by sneaker blogs due to the obvious Phoenix inspired color combination of black, purple and orange. The Shaq Attaq originally released in 1992 as Shaquille O’Neal’s first signature sneaker. At the time, it debuted Shaq’s personal Dunkman logo on the heel and featured the first Graphlite shank plate ever used on a Reebok basketball shoe. In 2013, the Shaq Attaq returned as a retro for the very first time. A number of colorways released, including new makeups, the classic home and away original color makeups, and of course, the Phoenix Suns inspired “Big Shaqtus” version. Since Shaq is no stranger to nicknames--Diesel, Big Man, Big Shamrock, Big Aristotle, Shaq Daddy, just to name a few--the Reebok Shaq Attaq “Big Shaqtus” uses one of his many to tie the colorway together with O’Neal and his history making career.', 2013, 'https://stockx.imgix.net/Reebok-Shaq-Attaq-Big-Shaqtus.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1538080256&w=2200', 'http://3app.kicksonfire.com/kofapp/upload/events_images/iphone_f7d377f3057a4d017f68775b7f7084265222e4bae600a.jpg', 'http://3app.kicksonfire.com/kofapp/upload/events_images/iphone_100c7ff033f5b766abde86c5fe26517f5222e4bb3c42f.jpg', 'http://3app.kicksonfire.com/kofapp/upload/events_images/iphone_f7d377f3057a4d017f68775b7f7084265222e4ba9e794.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Ex-O-Fit Clean Hi Bait', 'Reebok', 'x Ghostbusters x Stranger Things Vintage', 140, 'The BAIT x Stranger Things x Ghostbusters x Reebok Ex-O-Fit Vintage Hi sports a “Reebok” OG logo instead of the retro “Reebok Classics” logo and has a sponge vintage tongue, yellow glue marks, and vintage treatments all around the midsoles and the rest of the shoes. Retail price for this collaboration will be $140 and it will only be available at ComplexCon and online via raffle link in extremely limited quantities. 50 pairs will be available each day at ComplexCon on November 4th and 5th.', 2017, 'https://cdn5.kicksonfire.com/wp-content/uploads/2017/11/STRANGER-THINGS-1.jpg?x22822', 'https://cdn5.kicksonfire.com/wp-content/uploads/2017/11/STRANGER-THINGS-6.jpg?x22822', 'https://cdn5.kicksonfire.com/wp-content/uploads/2017/11/STRANGER-THINGS-5.jpg?x22822', 'https://cdn5.kicksonfire.com/wp-content/uploads/2017/11/STRANGER-THINGS-2.jpg?x22822');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Alien Stomper Mid Final Scene Pack', 'Reebok', 'Retro Yellow/Black-Gum', 325, 'The Reebok Alien Stomper Mid returned for another special release in 2017. Known as the "Final Scene" Pack, this two-shoe collection features two colorways of the futuristic Alien Stomper inspired by iconic elements from the final battle of the 1986 film, Aliens. Nicknamed the "Power Loader" and "Queen Alien" editions respectively, both pairs come in a special double box with parts of the original script engrained in it. The "Power Loader" edition, which draws inspiration from the machine Ellen Ripley used to defeat her enemy comes in a retro yellow and black colorway. Sporting a yellow-based upper with black accents, a full gum outsole and detailing tying back to the movie. The "Queen Alien" edition comes in all-black. Featuring a full patent leather upper with glow-in-the-dark hits and movie detailing. The Reebok Alien Stomper Mid "Final Scene" Pack was released on July 18th, 2017 retailing for $325. This pack should appease both fans of the sneaker as well as the Aliens film franchise. If you were lucky enough to snag a set, hit up the marketplace to see what they are going for. If you''re on the hunt for one, you can buy these Reebok''s online as we have people looking to sell them today.', 2017, 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200', 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img29.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200', 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img23.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200', 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Blaze of Glory Ronnie Fieg x Highsnobiety A Tale of Two Cities', 'Puma', 'Dark Navy', 160, 'The Blaze of Glory takes on a patriotic theme in navy, red and white, adjoined with a quilted upper and co-branding at the forefoot strap. Asymmetrical stars and strips in a debossed finish close the look along with a speckled Trinomic midsole.', 2015, 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Disc OG Ronnie Fieg "COA"', 'Puma', 'Black/Coral', 165, '2 years after Ronnie Fieg''s first successful Puma Disc, he created another masterful piece with the brand, the Ronnie Fieg x Puma Disc Blaze "Coat of Arms-Coral." Puma allowed RF to again put a twist on their Puma Disc Blaze model. And, yet again, RF symmetrized the toe box of the Coral Disc Blaze to make it more appealing to the growing, younger market. Fieg also added a new vamp and mudguard around the toe of the Coral Puma. Featuring 3M speckling against a black midsole, the Coral Puma Blaze was quick to catch the eyes of sneaker enthusiasts with it''s bold, yet sophisticated styling and retro fastening system. With an upper made of premium materials such as brushed nubuck, pebbled black leather and 3M accents, the newly designed Blazes retailed for a price of 165€ in Kith''s Paris COA pop-up shop throughout Men''s Fashion Week and $165 at both NYC Kith locations as well as their online web shop. The Coral COA were housed in a special co-branded box with COA crest. Released beside a Mint colorway of the same model, the Ronnie Fieg x Puma Disc Blaze "Coat of Arms-Coral" introduced a new color usage on RF''s signature toe box-highlighted styling.', 2014, 'https://stockx-360.imgix.net/puma-disc-ronnie-fieg-coa-red_TruView/Images/puma-disc-ronnie-fieg-coa-red_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/puma-disc-ronnie-fieg-coa-red_TruView/Images/puma-disc-ronnie-fieg-coa-red_TruView/Lv2/img21.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/puma-disc-ronnie-fieg-coa-red_TruView/Images/puma-disc-ronnie-fieg-coa-red_TruView/Lv2/img16.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/puma-disc-ronnie-fieg-coa-red_TruView/Images/puma-disc-ronnie-fieg-coa-red_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('RS-X Reinvention', 'Puma', 'Whisper White/Red Blast', 135, 'The latest evidence of the Puma takeover comes in the form of the Puma RS-X Reinvention, a chunky (but not overdoing) silhouette which taps a classic ''80s archive design, constructed with a fusion of materials including mesh, nubuck, and leather, the bold color-blocking sneaker features RS cushioning.', 2018, 'https://stockx-360.imgix.net/Puma-RS-X-Reinvention/Images/Puma-RS-X-Reinvention/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1552593893&w=2200', 'https://stockx-360.imgix.net/Puma-RS-X-Reinvention/Images/Puma-RS-X-Reinvention/Lv2/img25.jpg?auto=format,compress&q=90&updated_at=1552593893&w=2200', 'https://stockx-360.imgix.net/Puma-RS-X-Reinvention/Images/Puma-RS-X-Reinvention/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1552593893&w=2200', 'https://stockx-360.imgix.net/Puma-RS-X-Reinvention/Images/Puma-RS-X-Reinvention/Lv2/img09.jpg?auto=format,compress&q=90&updated_at=1552593893&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('R698 Low Ronnie Fieg TSP "Sakura"', 'Puma', 'Beet-Red/Pearl', 150, 'Released alongside the newly introduced RF698 Mid as part of the Sakura pack, the Ronnie Fieg x Puma R698 "Sakura" personified the early stages of the cherry blossoms in Japan. After a trip to Japan, Tokyo quickly became RF''s favorite city in the world, partly because of the Sakura Puma''s inspiration, the cherry blossom. Starting out as a white then transforming into a faint pink, before turning to deep cherry red, the cherry blossom only blooms for 7-10 days of the year, but during those days, those in Tokyo revere the tree for it''s beauty, just as sneaker enthusiasts do the Sakura R698. Constructed of lush microperforated pigskin suede throughout the upper, with a deep red toe box, the Cherry Blossom Pumas featured a gradient midsole that faded from the toe back to the mid-foot from the deep red to white. This was the first time that Ronnie Fieg had ever used a gradient midsole on one of his projects, and it is fitting he did so with the Japanese Cherry R698 as he truly captured the evolution of their blossom. Available at both Kith locations and online during the Spring of 2015 as part of the Tokyo Sakura Collection, the Ronnie Fieg x Puma R698 "Sakura" gave the essence of the beautiful cherry blossoms a form.', 2015, 'https://stockx-360.imgix.net/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Images/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Images/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Images/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Images/Puma-R698-Low-Ronnie-Fieg-Sakura_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Thunder Electric', 'Puma', 'Puma Black/White-Orange', 120, 'Inspired by Puma''s collaborations with Alexander McQueen, the Puma Thunder Electric mixes a nylon and leather upper with a gum-bottom outsole. Release date is June 21, 2018 at a retail price of $120.', 2018, 'https://stockx-360.imgix.net/Puma-Thunder-Electric-Black-White-Orange/Images/Puma-Thunder-Electric-Black-White-Orange/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Thunder-Electric-Black-White-Orange/Images/Puma-Thunder-Electric-Black-White-Orange/Lv2/img26.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Thunder-Electric-Black-White-Orange/Images/Puma-Thunder-Electric-Black-White-Orange/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Thunder-Electric-Black-White-Orange/Images/Puma-Thunder-Electric-Black-White-Orange/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('GV Special The Walking Dead', 'Puma', 'White/Yellow', 200, 'This special-edition PUMA collaboration, designed by notable sneaker customizer Alexander-John, is inspired by the storyline of the mysterious Whisperers from season nine of the hit television series. The design elements of the customized PUMA GV Special give a nod to The Walking Dead in subtle ways that only true fans can appreciate. Each shoe features hand-painted dirt patterns and custom leather detailing on both the tongue and the heel of the shoe. The biggest surprise for fans and sneaker enthusiasts alike comes when they open the box, to find a thrilling adornment of Alpha on the insoles.', 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/The-Walking-Dead-PUMA-GV-Special-Release-Date-4.jpg', 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/The-Walking-Dead-PUMA-GV-Special-Release-Date-5.jpg', 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/The-Walking-Dead-PUMA-GV-Special-Release-Date-3.jpg', 'https://stockx.imgix.net/Puma-GV-Special-The-Walking-Dead-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1554737048&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('RS-X', 'Puma', 'Transformer Optimus Prime', 100, 'Hasbros Inc. connects with PUMA for a footwear collaboration. The PUMA RS-X model takes on Bumblebee and Optimus Prime themes, with the former applying a “Quiet Shade/Cyber Yellow” combination. The latter shares a “Dazzling Blue/High Risk Red” mix and both incorporate textile, nubuck and mesh overlays. Its sole unit falls under the chunky category, subtly raising the model’s height. The famed Autobots insignia can be found on the heel, accompanied by PUMA’s signature logo on the tongue tab.', 2018, 'https://stockx-360.imgix.net/Puma-RS-X-Transformers-Optimus-Prime/Images/Puma-RS-X-Transformers-Optimus-Prime/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1540587427&w=2200', 'https://stockx-360.imgix.net/Puma-RS-X-Transformers-Optimus-Prime/Images/Puma-RS-X-Transformers-Optimus-Prime/Lv2/img27.jpg?auto=format,compress&q=90&updated_at=1540587427&w=2200', 'https://stockx-360.imgix.net/Puma-RS-X-Transformers-Optimus-Prime/Images/Puma-RS-X-Transformers-Optimus-Prime/Lv2/img22.jpg?auto=format,compress&q=90&updated_at=1540587427&w=2200', 'https://stockx-360.imgix.net/Puma-RS-X-Transformers-Optimus-Prime/Images/Puma-RS-X-Transformers-Optimus-Prime/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1540587427&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('RS-X', 'Puma', 'Transformer Bumblebee', 100, 'Hasbros Inc. connects with PUMA for a footwear collaboration. The PUMA RS-X model takes on Bumblebee and Optimus Prime themes, with the former applying a “Quiet Shade/Cyber Yellow” combination. The latter shares a “Dazzling Blue/High Risk Red” mix and both incorporate textile, nubuck and mesh overlays. Its sole unit falls under the chunky category, subtly raising the model’s height. The famed Autobots insignia can be found on the heel, accompanied by PUMA’s signature logo on the tongue tab.', 2018, 'https://images.solecollector.com/complex/images/fl_lossy,q_auto/c_crop,h_971,w_1667,x_0,y_345/c_scale,w_690,dpr_2.0/v1/vd0afrelfssjacxyvktw/hasbro-puma-rs-x-transformers-bumblebee-2', 'https://images.solecollector.com/complex/images/fl_lossy,q_auto/c_crop,h_857,w_1667,x_0,y_385/c_scale,w_690,dpr_2.0/v1/df7x4crm26qgrcc0ld0c/hasbro-puma-rs-x-transformers-bumblebee', 'https://images.solecollector.com/complex/images/fl_lossy,q_auto/c_crop,h_859,w_1667,x_0,y_372/c_scale,w_690,dpr_2.0/v1/hl9t1ag27lnbskhklevs/hasbro-puma-rs-x-transformers-bumblebee-3', 'https://images.solecollector.com/complex/images/fl_lossy,q_auto/c_crop,h_1106,w_1667,x_0,y_265/c_scale,w_690,dpr_2.0/v1/gunmr97ijaobpihkthme/hasbro-puma-rs-x-transformers-bumblebee-5');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Ultra Boost 4.0', 'Adidas', 'Game of Thrones House Targaryen', 180, 'Binge watch all seasons of Game of Thrones after copping the adidas Ultra Boost 4.0 Game of Thrones House Targaryen. These sneakers released in March 2019 and retailed for $180.', 2019, 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/1/3/136000_01.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/1/3/136000_02.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/1/3/136000_03.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/1/3/136000_04.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Yeezy Boost 350 v2', 'Adidas', 'Clay', 220, 'If you''re searching for a new sneaker with major drip, then cop the adidas Yeezy Boost 350 V2 Clay. This Yeezy Boost 350 comes with a clay upper with orange accents, translucent stripe with orange accents, clay midsole, and clay sole. These sneakers released in March 2019 and retailed for $220. Add another swaggy 350 V2 to the rotation and buy them on StockX today.', 2019, 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Clay/Images/Adidas-Yeezy-Boost-350-V2-Clay/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1551987026&w=1300', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Clay/Images/Adidas-Yeezy-Boost-350-V2-Clay/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1551987026&w=1300', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Clay/Images/Adidas-Yeezy-Boost-350-V2-Clay/Lv2/img21.jpg?auto=format,compress&q=90&updated_at=1551987026&w=1300', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Clay/Images/Adidas-Yeezy-Boost-350-V2-Clay/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1551987026&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Yeezy Boost 700', 'Adidas', 'Inertia', 300, 'Add heavy pressure on your favorite sneakerhead and cop the adidas Yeezy Boost 700 Inertia. This Yeezy Boost 700 comes with a grey upper, grey midsole with orange accents, and a white sole. These sneakers released in March 2019 and retailed for $300.', 2019, 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-700-Inertia/Images/Adidas-Yeezy-Boost-700-Inertia/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1551991286&w=1300', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-700-Inertia/Images/Adidas-Yeezy-Boost-700-Inertia/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1551991286&w=1300', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-700-Inertia/Images/Adidas-Yeezy-Boost-700-Inertia/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1551991286&w=1300', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-700-Inertia/Images/Adidas-Yeezy-Boost-700-Inertia/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1551991286&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Ultra Boost 2.0 ATR', 'Adidas', 'Glow in the Dark', 180, 'Adidas released this glow-in-the-dark edition of the Ultra Boost 2.0 ATR in September 2016. Sitting on a white Boost midsole, the performance runner sports a two-tone design that utilizes a mixture of grey and yellow coloring on the Primeknit upper. Those same hues are used individually on the midfoot cage and heel counter. The understated design takes on a new look when the lights go down, featuring neon-yellow glow-in-the-dark elements on the toe box and heel counter.', 2016, 'https://stockx-360.imgix.net/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Images/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Images/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Images/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Lv2/img14.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Images/Adidas-Ultra-Boost-ATR-Glow-In-The-Dark_TruView/Lv2/img07.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Yeezy 500 Salt', 'Adidas', 'Salt', 200, 'Don’t be salty, get out of your feelings, and cop a pair of the adidas Yeezy 500 Salt. With the potential of being the best Yeezy 500 colorway, these come with a salt upper, a salt midsole, and a salt sole.', 2018, 'https://stockx-360.imgix.net/Adidas-Yeezy-500-Salt/Images/Adidas-Yeezy-500-Salt/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1544024798&w=2200', 'https://stockx-360.imgix.net/Adidas-Yeezy-500-Salt/Images/Adidas-Yeezy-500-Salt/Lv2/img27.jpg?auto=format,compress&q=90&updated_at=1544024798&w=2200', 'https://stockx-360.imgix.net/Adidas-Yeezy-500-Salt/Images/Adidas-Yeezy-500-Salt/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1544024798&w=2200', 'https://stockx-360.imgix.net/Adidas-Yeezy-500-Salt/Images/Adidas-Yeezy-500-Salt/Lv2/img11.jpg?auto=format,compress&q=90&updated_at=1544024798&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Yeezy Boost 350 v2', 'Adidas', 'Cream White', 220, 'Does cash rule everything around you? If so, then it would be wise to cop the adidas Yeezy Boost 350 Cream White. Returning for round two with a huge restock, the luminous colored Yeezy Boost 350 has a cream white upper, core white midsole, and a camouflaged “SPLY-350” branding across the stripe on the sides.', 2017, 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Cream-White/Images/Adidas-Yeezy-Boost-350-V2-Cream-White/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1539789713&w=2200', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Cream-White/Images/Adidas-Yeezy-Boost-350-V2-Cream-White/Lv2/img26.jpg?auto=format,compress&q=90&updated_at=1539789713&w=2200', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Cream-White/Images/Adidas-Yeezy-Boost-350-V2-Cream-White/Lv2/img21.jpg?auto=format,compress&q=90&updated_at=1539789713&w=2200', 'https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Cream-White/Images/Adidas-Yeezy-Boost-350-V2-Cream-White/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1539789713&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Solar', 'Adidas', 'Hu Pharrell Chinese New Year', 150, 'The Spring Festival is here, so cop the new adidas Solar Hu Pharrell Chinese New Year (2019). This Solar Hu comes with a red upper plus black and gold accents, white midsole, and black sole. These sneakers released in January 2019 and retailed for $150. Make Pharrell proud and cop these on StockX today.', 2019, 'https://stockx-360.imgix.net/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Images/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549854774&w=2200', 'https://stockx-360.imgix.net/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Images/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Lv2/img31.jpg?auto=format,compress&q=90&updated_at=1549854774&w=2200', 'https://stockx-360.imgix.net/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Images/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1549854774&w=2200', 'https://stockx-360.imgix.net/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Images/Adidas-Solar-Hu-Pharrell-Chinese-New-Year-2019/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1549854774&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Ultra Boost 1.0', 'Adidas', 'Wood Wood Black', 180, 'As part of adidas’ 2016 Consortium world tour, Danish streetwear brand Wood Wood’s Ultra Boost 1.0 design is inspired by scientist’s detection of gravitational waves in the afterglow of the Big Bang. The last untested prediction of Einstein’s theory of relativity finds its way into this black Primeknit.', 2016, 'https://stockx-360.imgix.net/adidas-ultra-boost-wood-wood-black_TruView/Images/adidas-ultra-boost-wood-wood-black_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/adidas-ultra-boost-wood-wood-black_TruView/Images/adidas-ultra-boost-wood-wood-black_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/adidas-ultra-boost-wood-wood-black_TruView/Images/adidas-ultra-boost-wood-wood-black_TruView/Lv2/img13.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/adidas-ultra-boost-wood-wood-black_TruView/Images/adidas-ultra-boost-wood-wood-black_TruView/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('ZX 4000 4D Carbon', 'Adidas', 'Carbon/Semi Solar Yellow', 350, 'As a nod to the ’80s ZX running shoes, adidas gave their ZX 4000 a modernized makeover with the debut of the adidas ZX 4000 4D, which debuts on February 9th.Adding to its lineup, the Three Stripes will be releasing an upcoming “Carbon” colorway. The shoe comes crafted in a knit upper with suede overlays keeping true to the original design updated with a digitally-printed midsole.', 2019, 'https://stockx-360.imgix.net/Adidas-ZX-4000-4D-Carbon/Images/Adidas-ZX-4000-4D-Carbon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1551111806&w=2200', 'https://stockx-360.imgix.net/Adidas-ZX-4000-4D-Carbon/Images/Adidas-ZX-4000-4D-Carbon/Lv2/img24.jpg?auto=format,compress&q=90&updated_at=1551111806&w=2200', 'https://stockx-360.imgix.net/Adidas-ZX-4000-4D-Carbon/Images/Adidas-ZX-4000-4D-Carbon/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1551111806&w=2200', 'https://stockx-360.imgix.net/Adidas-ZX-4000-4D-Carbon/Images/Adidas-ZX-4000-4D-Carbon/Lv2/img07.jpg?auto=format,compress&q=90&updated_at=1551111806&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Gel-Lyte 3.1 Ronnie Fieg', 'Asics', 'Salmon', 2016, 'Released as part of the ‘Legends Day’ pack in November 2016, the Ronnie Fieg x Gel Lyte 3.1 "Salmon" features a salmon-colored premium pigskin suede upper with white accents on the medial toe. Other details include a Kith 5-Year logo on the heel, three additional lace options, a white midsole with visible blue Gel technology, and a light grey outsole.', 2016, 'https://stockx-360.imgix.net/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Images/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Images/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Images/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Images/asics-gel-lyte-3pt1-ronnie-fieg-salmon_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Gel-Lyte 3 Afew x Beams', 'Asics', 'Orange Koi', 211, 'The collaboration between German footwear retailers Afew is a fitting tribute to the 25th anniversary of the Asics Gel Lyte III. The limited edition sneaker comes in full battle gear from the Bento box packaging, the design accents, and colorways, and the Japanese-inspired freebies included in each pair. What further makes this $180 per pair shoe much coveted is its limited edition status with only close to 2000 copies produced with many sneaker fans wanting this kicks in their collection', 2018, 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Images/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546586103&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Images/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1546586103&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Images/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1546586103&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Images/Asics-Gel-Lyte-III-Afew-X-Beams-Orange-Koi/Lv2/img16.jpg?auto=format,compress&q=90&updated_at=1546586103&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Gel-Diablo', 'Asics', 'Ronnie Fieg Volcano 2.0', 175, 'This Ronnie Fieg designed ASICS Gel Diablo "Volcano 2.0" was the Kith founder’s first ever design for the Gel Diablo — a silhouette which first dropped in 1995. An alternate take on Fieg’s classic 2013 Gel Lyte 5 "Volcano,"" the shoe features a premium nubuck, sport mesh, and pigskin suede construction with a Parchment, Volcano, Ash Pink, and navy colorway. It initially dropped as a 500 pair KITHstrike in early April 2017 before 500 additional pairs were released alongside the Ronnie Fieg x Gel Lyte 3 "Volcano 2.0" in the ‘Volcano 2.0’ pack.', 2017, 'https://stockx-360.imgix.net/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Images/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Images/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Images/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Lv2/img14.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Images/asics-gel-diablo-ronnie-fieg-volcano-2-0_TruView/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Gel-Lyte Speed', 'Asics', 'Ubiq Cool Breeze', 140, 'The UBIQ x ASICS Gel Lyte Speed “Cool Breeze” is the latest collaboration between both brands that is designed perfectly for the summer time.This UBIQ x ASICS Gel Lyte Speed “Cool Breeze” is inspired by the positive and refreshing vibes we all experience during the summer months. The clear Blue skies and rejuvenating feeling when we step into the cool waters of the ocean served as the muse when developing this project. Every time you slip on a pair of the “Cool Breeze,” they want you to remember the tranquil feeling of seeing Crystal Blue skies, and touching the Teal Blue waters.', 2015, 'https://stockx-360.imgix.net/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Images/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549855968&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Images/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Lv2/img21.jpg?auto=format,compress&q=90&updated_at=1549855968&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Images/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Lv2/img15.jpg?auto=format,compress&q=90&updated_at=1549855968&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Images/Asics-Gel-Lyte-Speed-Ubiq-Cool-Breeze_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1549855968&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Onitsuka Tiger Colorado 85 Bait Bruce Lee', 'Asics', 'Yellow/Black', 160, 'Californian streetwear retailer Bait teamed up with Onitsuka Tiger for this tribute to Bruce Lee to celebrate what would have been his 75th birthday in 2015. Sporting a colorway inspired by the yellow and black jumpsuit and Onitsuka Tiger Corsairs that Lee wore in Game of Death, the shoe features a premium nubuck upper with leather tiger stripes, a leather lining, and a speckled sole. It also comes with Bruce Lee branding on the tongue, his signature on the yellow lace aglets, embroidered Onitsuka Tiger and Bruce Lee kickman logos on the heel, and custom insoles with a Bruce Lee 75th-anniversary logo.', 2018, 'https://stockx-360.imgix.net/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Images/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549856040&w=2200', 'https://stockx-360.imgix.net/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Images/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Lv2/img29.jpg?auto=format,compress&q=90&updated_at=1549856040&w=2200', 'https://stockx-360.imgix.net/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Images/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Lv2/img22.jpg?auto=format,compress&q=90&updated_at=1549856040&w=2200', 'https://stockx-360.imgix.net/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Images/Asics-Onitsuka-Tiger-Colorado-85-Bait-Bruce-Lee/Lv2/img09.jpg?auto=format,compress&q=90&updated_at=1549856040&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Gel-Saga Diamond Supply Co x Ronnie Fieg "Tiffany" Black', 'Asics', 'Black/Aqua', 165, '"Bringing the East and West coasts together, KITH-founder Ronnie Fieg and Diamond Supply Co. have teamed up with ASICS to reimagine both the Gel Saga silhouettes with Diamond’s iconic “Diamond Blue” hue. Utilizing the previously mentioned shade about its pigskin suede toe, lace eyestay and striped branding, the Gel Saga offering is equipped with blackened leather sprucing up its heel and interior lining."', 2015, 'https://stockx-360.imgix.net/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-saga-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Gel Lyte V', 'Adidas', 'Aqua/White-Grey', 175, 'Bringing the East and West coasts together, KITH-founder Ronnie Fieg and Diamond Supply Co. have teamed up with ASICS to reimagine Gel Lyte V silhouettes with Diamond’s iconic “Diamond Blue” hue. Its Gel Lyte V dips the large majority of its microperforated pigskin suede upper in the refreshing blue hue while metallic silver fiberglass material, leather and hits of 3M add to the aesthetic appeal.', 2015, 'https://stockx-360.imgix.net/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549856028&w=2200', 'https://stockx-360.imgix.net/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1549856028&w=2200', 'https://stockx-360.imgix.net/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img15.jpg?auto=format,compress&q=90&updated_at=1549856028&w=2200', 'https://stockx-360.imgix.net/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Images/asics-gel-lyte-v-diamond-supply-co-x-ronnie-fieg-tiffany_TruView/Lv2/img05.jpg?auto=format,compress&q=90&updated_at=1549856028&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Gel Lyte 3 Titolo "Papercut"', 'Asics', 'Black/Red-White', 160, 'Titolo is back with a brand new collaborative effort atop the ever-classic Asics Gel Lyte III. Named the “Papercut”, this isn’t an homage to the stingingly painful cuts on your fingertips, but instead references the art of Scherenschnitt, or paper cutting. In an homage to the Switzerland boutique’s Zurich shop, this Gel Lyte III references the intricate pattern on the ceiling of the store with a unique insole while the black and white floral pattern extends to the neoprene mesh and side panel striping. The premium black base is in an effort to continue the premium Tiger branding that was recently introduced.', 2015, 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Titolo-Papercut/Images/Asics-Gel-Lyte-III-Titolo-Papercut/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546679336&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Titolo-Papercut/Images/Asics-Gel-Lyte-III-Titolo-Papercut/Lv2/img30.jpg?auto=format,compress&q=90&updated_at=1546679336&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Titolo-Papercut/Images/Asics-Gel-Lyte-III-Titolo-Papercut/Lv2/img17.jpg?auto=format,compress&q=90&updated_at=1546679336&w=2200', 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Titolo-Papercut/Images/Asics-Gel-Lyte-III-Titolo-Papercut/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1546679336&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Retro 11 ', 'Jordan', 'Concord', 220, 'Jordan Brand is reaching harder than MJ on Space Jam for the sneaker of the year crown by releasing the Jordan 11 Retro Concord (2018). This Iconic Jordan 11 colorway is showcasing a white upper with black accents, white midsole, and a freezing cold translucent sole. These sneakers released in December 2018 and retailed for $220. Revisit the dominant legacy MJ left behind.', 2018, 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/805882_2.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/805882_4.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/805882_1.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/805882_3.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Retro 3', 'Jordan', 'Black Cement', 200, 'One of the most anticipated releases of 2018, the Air Jordan 3 Retro OG marked the first time original "Nike Air" branding was featured on the "Black Cement" AJ 3 since it''s 2001 retro. Jordan stuck to the mantra of “if it aint broke, don’t fix it,” on these, staying true to the OG with a black-based leather upper with cement grey, fire red, and white accents, finished off by the iconic elephant print detailing.', 2018, 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/803229_01.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/803229_02.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/803229_03.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/803229_04.jpg');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Retro 6', 'Jordan', 'Black/Infrared', 200, 'Make sure your head isn’t in the beam while trying to grab the Jordan 6 Retro Black Infrared (2019). This AJ6 come with a black upper, black midsole plus red accents, and a translucent sole. These sneakers released in February 2019 and retailed for $200.', 2019, 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1300', 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1300', 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1300', 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Travis Scott Air Jordan 4 Retro', 'Jordan', 'University Blue/Black-Varsity', 225, 'The only way to describe the Travis Scott Air Jordan 4 Retros properly would be to use the rappers own adlib: la flame. These Jordan 4s were made in collaboration with rapper, Travis Scott and nicknamed the “Cactus Jack” edition. Similar in design to the infamous Eminem pair, these feature a lighter shade of blue suede on the upper. Black accents, a red liner, paint splatter detailing, a white midsole and “Cactus Jack” branding on the back heel tab finish things off for this pair. These dropped in June of 2018 for $225 and came exclusively in men’s sizes. If you’re a fan of Travis Scott and the AJ 4, this pair is another must-have.', 2019, 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Images/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Images/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Lv2/img26.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Images/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Images/Air-Jordan-4-Retro-Travis-Scott-Cactus-Jack/Lv2/img17.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Jordan 4 Retro UNDFTD', 'Jordan', 'Olive-oiled Suede-Flight Satin Undftd', 17500, 'The Undefeated Air Jordan 4 originally debuted in 2005 and was limited to only 72 pairs. Each pair was given out to friends and family and never actually released at retail. This was the first time Jordan Brand teamed up for a collaboration with a third party.', 2005, 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-UNDFTD_TruView/Images/Air-Jordan-4-Retro-UNDFTD_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-UNDFTD_TruView/Images/Air-Jordan-4-Retro-UNDFTD_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-UNDFTD_TruView/Images/Air-Jordan-4-Retro-UNDFTD_TruView/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-UNDFTD_TruView/Images/Air-Jordan-4-Retro-UNDFTD_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Jordan 4 Retro Black Cement', 'Jordan', 'Black/Fire Red-Cement Grey', 160, 'Because this is an older release, deadstock pairs may come with yellowed wings due to natural aging', 2012, 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Images/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1551048119&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Images/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1551048119&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Images/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Lv2/img15.jpg?auto=format,compress&q=90&updated_at=1551048119&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Images/Air-Jordan-4-Retro-Black-Cement-2012_TruView/Lv2/img07.jpg?auto=format,compress&q=90&updated_at=1551048119&w=2200');

INSERT INTO shoes(shoe_model, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Jordan 3 Retro', 'Jordan', 'White/Cement Grey-Fire Red', 150, 'The Nike Air Jordan III Retro White/Cement from 2011 was a long overdue release. By 2011, the White Cement Jordan III had sat in the vault at Nike since the 2003 release. Which meant, for most sneakerheads, you had already burned through at least a pair or two of the iconic Jordan 3 sneaker. This variation of the White Cement Jordan III Retro was the first time it became a problem that the “Nike Air” wasn’t on the heel of the shoe. Purists might have been offish with the 2003 release but it became mainstream to complain about the Jumpman on the heel thanks to platforms like Twitter and Instagram. Outside of sneaker enthusiasts, however, it didn’t matter because the memories of the 1988 Dunk Contest, and MJ taking off from the free throw line still conjured up memories for Chicago Bulls and Michael Jordan fans. The 2011 Jordan III sold well initially, selling out in most places rather quickly but restocks meant getting your hands on a pair wasn’t impossible, especially considering the latte January release that meant plenty of holiday money burning a hole in the pockets of sneaker enthusiasts. In terms of quality and availability, the 2011 Air Jordan Retro 3 White Cement might be the lowest of all the original colorway Jordan 3s but it will always have a mass appeal that most sneakers will never have thanks to Michael Jordan.', 2011, 'https://stockx-360.imgix.net/Air-Jordan-3-Retro-White-Cement-2011/Images/Air-Jordan-3-Retro-White-Cement-2011/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546584106&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-3-Retro-White-Cement-2011/Images/Air-Jordan-3-Retro-White-Cement-2011/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1546584106&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-3-Retro-White-Cement-2011/Images/Air-Jordan-3-Retro-White-Cement-2011/Lv2/img16.jpg?auto=format,compress&q=90&updated_at=1546584106&w=2200', 'https://stockx-360.imgix.net/Air-Jordan-3-Retro-White-Cement-2011/Images/Air-Jordan-3-Retro-White-Cement-2011/Lv2/img09.jpg?auto=format,compress&q=90&updated_at=1546584106&w=2200');


CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
    "sess" json NOT NULL,
    "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;